In [2]:
!pip install numpy scipy
import numpy as np
from collections import OrderedDict
from scipy.spatial import distance as dist

rects=[[189.42716266,  27.24091831, 207.80059182,  61.64119437, 309.],
       [162.73882115,  37.55935711, 184.11430641,  85.98845161, 287. ]]


Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.


In [3]:
inputCentroids = np.zeros((len(rects), 2), dtype="int")

for (i, (startX, startY, endX, endY, id)) in enumerate(rects):
    # use the bounding box coordinates to derive the centroid
    cX = int((startX + endX) / 2.0)
    cY = int((startY + endY) / 2.0)
    inputCentroids[i] = (cX, cY)
inputCentroids

objects = OrderedDict()
for i in range(0, len(inputCentroids)):
    objects[i] = inputCentroids[i]
objects

OrderedDict([(0, array([198,  44])), (1, array([173,  61]))])

In [14]:
from scipy.spatial import distance as dist

np.array(objectCentroids)

array([[198,  44],
       [173,  61]])

In [15]:
objectIDs = list(objects.keys())
objectCentroids = list(objects.values())
objectIDs

[0, 1]

In [49]:
D = dist.cdist(inputCentroids, inputCentroids)
D
aa=np.array( [[0,0], [1,1]] )
ab=np.array( [[0,1], [1,2] ] )
d=dist.cdist( aa, ab )
d

array([[1.        , 2.23606798],
       [1.        , 1.        ]])

In [43]:
[d[:,q] for q in range(len(ab))]

[array([1., 1.]), array([2.23606798, 1.        ])]

In [17]:
np.array(objectCentroids)==np.array(inputCentroids)

array([[ True,  True],
       [ True,  True]])

In [56]:
d[:, 1]

array([2.23606798, 1.        ])